### ISSUE TITLE
My game crashes when:

### ISSUE THREAD

**Issue by vinnyg0621** [Aeltumn/Chisels-and-Bits-2#27]
![2020-01-04_18 14 07](https://user-images.githubusercontent.com/57818441/71774186-289b9d00-2f1f-11ea-8374-21b224917a6d.png)
**---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/4/20 6:15 PM
Description: Unexpected error

java.lang.RuntimeException: Can't set mode of item stack to selected item mode if item is not a storage item.
	at nl.dgoossens.chiselsandbits2.common.utils.ItemModeUtil.changeItemMode(ItemModeUtil.java:68) ~[?:alpha4] {re:classloading}
	at nl.dgoossens.chiselsandbits2.client.gui.ItemModeMenu.triggerEffect(ItemModeMenu.java:82) ~[?:alpha4] {re:classloading}
	at nl.dgoossens.chiselsandbits2.api.radial.RadialMenu.tick(RadialMenu.java:172) ~[?:alpha4] {re:classloading}
	at nl.dgoossens.chiselsandbits2.api.radial.RadialMenu$RadialMenuEvent.onTick(RadialMenu.java:231) ~[?:alpha4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_72_RadialMenuEvent_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:109) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1395) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.107.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$394/2042917213.call(Unknown Source) [forge-1.14.4-28.1.107.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at nl.dgoossens.chiselsandbits2.common.utils.ItemModeUtil.changeItemMode(ItemModeUtil.java:68)
	at nl.dgoossens.chiselsandbits2.client.gui.ItemModeMenu.triggerEffect(ItemModeMenu.java:82)
	at nl.dgoossens.chiselsandbits2.api.radial.RadialMenu.tick(RadialMenu.java:172)
	at nl.dgoossens.chiselsandbits2.api.radial.RadialMenu$RadialMenuEvent.onTick(RadialMenu.java:231)
	at net.minecraftforge.eventbus.ASMEventHandler_72_RadialMenuEvent_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:109)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['vinnyg0621'/23, l='MpServer', x=-222.91, y=64.44, z=214.12]]
	Chunk stats: Client Chunk Cache: 121, 49
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-224,64,208), Chunk: (at 0,4,0 in -14,13; contains blocks -224,0,208 to -209,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 32880 game time, 32880 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$394/2042917213.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 729020456 bytes (695 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.107.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.107.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.107.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.107.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.107.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.107
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		forge-1.14.4-28.1.107-client.jar Minecraft {minecraft@1.14.4 DONE}
		Its-the-Little-Things-Mod-1.14.4.jar It's the little things {itlt@1.14.4-1.0.2 DONE}
		AmbientSounds_v3.0.9_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		BiomesOPlenty-1.14.4-9.0.0.236-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.236 DONE}
		slopes-1.0.0-mc1.14.4.jar Slopes {slopes@1.0.0 DONE}
		cfm-7.0.0-pre15-mc1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 DONE}
		CreativeCore_v2.0.1_mc1.14.4.jar CreativeCore {creativecore@2.0.0 DONE}
		MineTraps-Mod-1.14.4.jar MineTraps {minetraps@2.0.0pre1 DONE}
		Advanced-Mining-Dimension-Mod-1.14.4.jar Mining World {mining_dimension@1.14.4-1.0.2 DONE}
		Snow-Variants-Mod-1.14.4.jar Snow Variants {snowvariants@1.14.4-1.0.2 DONE}
		Extended-Slabs-1.14.4.jar Extended Slabs {extendedslabs@0.1.0-beta DONE}
		I-Like-Wood-Mod-1.14.4.jar I Like Wood {ilikewood@1.1.2.0 DONE}
		Fairy-Lights-Mod-1.14.4.jar Fairy Lights {fairylights@2.1.13 DONE}
		forge-1.14.4-28.1.107-universal.jar Forge {forge@28.1.107 DONE}
		Quick-Leaf-Decay-Mod-1.14.4.jar Quick Leaf Decay {quickleafdecay@1.2.5 DONE}
		The-Flying-Things-Mod-1.14.4.jar The Flying Things {flying_things@1.8.4 DONE}
		Extended-Lights-Mod-1.14.4.jar Extended Lights {extlights@1.2 DONE}
		The-RC-Mod-1.14.4.jar The RC Mod {thercmod@4.0.0.0 DONE}
		Mubble-Mod-1.14.4.jar Mubble {mubble@1.4-pre9 DONE}
		Comforts-Mod-1.14.4.jar Comforts {comforts@FORGE-1.14.4-2.0-beta3 DONE}
		chiselsandbits2-alpha4.jar Chisels & Bits 2 {chiselsandbits2@alpha4 DONE}
	Launched Version: 1.14.4-forge-28.1.107
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 25.20.100.6472, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla, file/Better font 1.14.4
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz**

It crashed right when I was trying to place yellow terracotta bits on a tiny-house's roof.

**Comment by Aeltumn** [comment]
This crash should no longer occur in the next alpha, thanks for reporting it!

If you want to try and avoid the crash, it can happen if you switch item modes (or if item modes are automatically changed like when a new bit type is selected) you need to make sure not to switch which item you are holding. It should work much better in the next alpha.
