### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by TomWhoo** [Aeltumn/Chisels-and-Bits-2#32]
I keep getting this crash whenever I preform actions with the mod
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 1/23/20 7:24 AM
Description: Unexpected error

java.lang.RuntimeException: Can't set mode of item stack to selected item mode if item is not a storage item.
	at nl.dgoossens.chiselsandbits2.common.utils.ItemModeUtil.changeItemMode(ItemModeUtil.java:68) ~[?:alpha4] {re:classloading}
	at nl.dgoossens.chiselsandbits2.client.gui.ItemModeMenu.triggerEffect(ItemModeMenu.java:82) ~[?:alpha4] {re:classloading}
	at nl.dgoossens.chiselsandbits2.api.radial.RadialMenu.tick(RadialMenu.java:172) ~[?:alpha4] {re:classloading}
	at nl.dgoossens.chiselsandbits2.api.radial.RadialMenu$RadialMenuEvent.onTick(RadialMenu.java:231) ~[?:alpha4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_154_RadialMenuEvent_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:109) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1395) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.111.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$420/523528914.call(Unknown Source) [forge-1.14.4-28.1.111.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at nl.dgoossens.chiselsandbits2.common.utils.ItemModeUtil.changeItemMode(ItemModeUtil.java:68)
	at nl.dgoossens.chiselsandbits2.client.gui.ItemModeMenu.triggerEffect(ItemModeMenu.java:82)
	at nl.dgoossens.chiselsandbits2.api.radial.RadialMenu.tick(RadialMenu.java:172)
	at nl.dgoossens.chiselsandbits2.api.radial.RadialMenu$RadialMenuEvent.onTick(RadialMenu.java:231)
	at net.minecraftforge.eventbus.ASMEventHandler_154_RadialMenuEvent_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:109)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['TomWho'/198, l='MpServer', x=-16.02, y=75.00, z=-82.20]]
	Chunk stats: Client Chunk Cache: 1225, 961
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (32,64,-39), Chunk: (at 0,4,9 in 2,-3; contains blocks 32,0,-48 to 47,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1247898 game time, 775831 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$420/523528914.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3406629688 bytes (3248 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.111.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.111.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.111.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.111.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.111.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.111
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		forge-1.14.4-28.1.111-client.jar Minecraft {minecraft@1.14.4 DONE}
		Useful-Backpacks-Mod-1.14.4.jar Useful Backpacks {usefulbackpacks@1.7.0.34 DONE}
		AmbientSounds_v3.0.14_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		SoundControl-1.14.4-0.0.1.0.jar §3Dynamic Surroundings
§eSound Control {sndctrl@1.14.4-0.0.1.0 DONE}
		Biomes-O-Plenty-Mod-1.14.4.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.256 DONE}
		extcaves-1.4.2 (1).jar Extended Caves {extcaves@1.4.2 DONE}
		Cosmetic-Beds-Mod-1.14.4.jar Cosmetic Beds {cosmeticbeds@FORGE-1.14.4-2.0 DONE}
		Xaeros_Minimap_1.19.3_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.19.3 DONE}
		More-Ores-In-ONE-Mod-1.14.4.jar More Ores in ONE {moreoresinone@1.4 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		CookingForBlockheads_1.14.4-7.4.2.jar Cooking for Blockheads {cookingforblockheads@7.4.2 DONE}
		good-nights-sleep-1.14.4-1.0.1.jar Good Night's Sleep {goodnightsleep@1.0.1 DONE}
		chiselsandbits2-alpha4.jar Chisels & Bits 2 {chiselsandbits2@alpha4 DONE}
		jei-1.14.4-6.0.0.26.jar Just Enough Items {jei@6.0.0.26 DONE}
		themidnight-0.4.6.jar The Midnight {midnight@0.4.6 DONE}
		DungeonCrawl-1.14.4-1.5.2.jar Dungeon Crawl {dungeoncrawl@1.5.2 DONE}
		betteranimalsplus-1.14.4-8.0.0.jar Better Animals Plus {betteranimalsplus@8.0.0 DONE}
		The-Endergetic-Expansion-1.14.4-v1.0.jar The Endergetic Expansion {endergetic@1.0 DONE}
		U-Team-Core-1.14.4.jar U Team Core {uteamcore@2.7.0.129 DONE}
		cfm-7.0.0-pre15-mc1.14.4 (2).jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 DONE}
		XL-Food-Mod-1.14.4-2.2.1.jar XL Food Mod {xlfoodmod@2.2.1 DONE}
		Charm-1.14.4-1.4.3.jar Charm {charm@1.14.4-1.4.3 DONE}
		forge-1.14.4-28.1.111-universal.jar Forge {forge@28.1.111 DONE}
		Quark-r2.0-203 (1).jar Quark {quark@r2.0-203 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		simpleores-1.14.4-2.0.6.0.jar Simple Ores {simpleores@1.14.4-2.0.6.0 DONE}
		SuperTools-1.6b.jar Super Tools {supertools@1.6b DONE}
	Launched Version: 1.14.4-forge-28.1.111
	LWJGL: 3.2.2 build 10
	OpenGL: NVS 4200M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.74, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz

**Comment by Aeltumn** [comment]
This issue should be fixed in the next alpha!
