### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by TallMonkee** [Aeltumn/Chisels-and-Bits-2#58]
Whenever I try to load my world my game crashes and the launcher displays this error message:

The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Ticking block entity

**Comment by Aeltumn** [comment]
Could you send the full crash log?

**Comment by TallMonkee** [comment]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 26/07/20 22:38
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at nl.dgoossens.chiselsandbits2.client.ChiselEvent.onPlayerInteract(ChiselEvent.java:61) ~[?:0.5.2a] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_48_ChiselEvent_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:775) ~[?:?] {re:classloading}
	at com.simibubi.create.modules.contraptions.components.deployer.DeployerHandler.activateInner(DeployerHandler.java:165) ~[?:mc1.14.4_v0.2.2b] {re:classloading}
	at com.simibubi.create.modules.contraptions.components.deployer.DeployerHandler.activate(DeployerHandler.java:100) ~[?:mc1.14.4_v0.2.2b] {re:classloading}
	at com.simibubi.create.modules.contraptions.components.deployer.DeployerTileEntity.activate(DeployerTileEntity.java:269) ~[?:mc1.14.4_v0.2.2b] {re:classloading}
	at com.simibubi.create.modules.contraptions.components.deployer.DeployerTileEntity.func_73660_a(DeployerTileEntity.java:198) ~[?:mc1.14.4_v0.2.2b] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at nl.dgoossens.chiselsandbits2.client.ChiselEvent.onPlayerInteract(ChiselEvent.java:61)
	at net.minecraftforge.eventbus.ASMEventHandler_48_ChiselEvent_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:775)
	at com.simibubi.create.modules.contraptions.components.deployer.DeployerHandler.activateInner(DeployerHandler.java:165)
	at com.simibubi.create.modules.contraptions.components.deployer.DeployerHandler.activate(DeployerHandler.java:100)
	at com.simibubi.create.modules.contraptions.components.deployer.DeployerTileEntity.activate(DeployerTileEntity.java:269)
	at com.simibubi.create.modules.contraptions.components.deployer.DeployerTileEntity.func_73660_a(DeployerTileEntity.java:198)

-- Block entity being ticked --
Details:
	Name: create:deployer // com.simibubi.create.modules.contraptions.components.deployer.DeployerTileEntity
	Block: Block{create:deployer}[axis_along_first=false,facing=east]
	Block location: World: (12,53,-220), Chunk: (at 12,3,4 in 0,-14; contains blocks 0,0,-224 to 15,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Block: Block{create:deployer}[axis_along_first=false,facing=east]
	Block location: World: (12,53,-220), Chunk: (at 12,3,4 in 0,-14; contains blocks 0,0,-224 to 15,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:621)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level name: Sick World Innit G
	Level seed: 7925443192673619200
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-64,74,-239), Chunk: (at 0,4,1 in -4,-15; contains blocks -64,0,-240 to -49,255,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 5936198 game time, 23500 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3312726176 bytes (3159 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		premium-wood-1.14.4-1.1.0.jar Premium Wood {premium_wood@1.1.0 DONE}
		immersive-portals-0.15(for+mc+1.14+with+forge).jar Immersive Portals {immersive_portals@0.15 DONE}
		NomadicTents-1.14.4-10.1.1.jar Nomadic Tents {nomadictents@10.1.1 DONE}
		AmbientSounds_v3.0.16_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		playerplates-1.14.4-forge-1.1.0.jar Player Plates {playerplates@1.14.4-forge-1.1.0 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		infinitemusic-1.14.4-1.0.0.jar Infinite Music {infinitemusic@1.0.0 DONE}
		worldedit-forge-mc1.14.4-7.0.1.jar WorldEdit {worldedit@7.0.1;61bc012 DONE}
		create-mc1.14.4_v0.2.2b.jar Create {create@mc1.14-0.2.2b DONE}
		BetterFoliage-2.5.0-Forge-1.14.4.jar Better Foliage {betterfoliage@2.5.0 DONE}
		chiselsandbits2-0.5.2a.jar Chisels & Bits 2 {chiselsandbits2@0.5.2a DONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge, mod:immersive_portals, mod:worldedit, mod:ambientsounds, mod:create, mod:playerplates, mod:infinitemusic (incompatible), mod:nomadictents, mod:betterfoliage, mod:premium_wood, mod:chiselsandbits2
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27016
	OpenGlRenderer: Radeon (TM) RX 480 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Aeltumn** [comment]
This appears to be a crash due related to the Create mod being installed. I'll add it to the list of bugs to fix.

**Comment by Emile2020** [comment]
I got it to
